// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tkoi_build_csr
List tkoi_build_csr(IntegerVector from, IntegerVector to, NumericVector weight, int n);
RcppExport SEXP _tkoi_tkoi_build_csr(SEXP fromSEXP, SEXP toSEXP, SEXP weightSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(tkoi_build_csr(from, to, weight, n));
    return rcpp_result_gen;
END_RCPP
}
// tkoi_ppr_null
List tkoi_ppr_null(List csr, IntegerVector observed_node, NumericVector observed_weight, IntegerMatrix null_node, NumericVector null_weight, double damping, double tol, int max_iter, int n_threads, int max_block, bool keep_null, Nullable<Function> progress);
RcppExport SEXP _tkoi_tkoi_ppr_null(SEXP csrSEXP, SEXP observed_nodeSEXP, SEXP observed_weightSEXP, SEXP null_nodeSEXP, SEXP null_weightSEXP, SEXP dampingSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP n_threadsSEXP, SEXP max_blockSEXP, SEXP keep_nullSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type csr(csrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type observed_node(observed_nodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observed_weight(observed_weightSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type null_node(null_nodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type null_weight(null_weightSEXP);
    Rcpp::traits::input_parameter< double >::type damping(dampingSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type max_block(max_blockSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_null(keep_nullSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(tkoi_ppr_null(csr, observed_node, observed_weight, null_node, null_weight, damping, tol, max_iter, n_threads, max_block, keep_null, progress));
    return rcpp_result_gen;
END_RCPP
}
// tkoi_seed_reach
List tkoi_seed_reach(IntegerVector row_ptr, IntegerVector col, IntegerVector seeds, int n_threads);
RcppExport SEXP _tkoi_tkoi_seed_reach(SEXP row_ptrSEXP, SEXP colSEXP, SEXP seedsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type row_ptr(row_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type col(colSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tkoi_seed_reach(row_ptr, col, seeds, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// tkoi_sample_null
IntegerMatrix tkoi_sample_null(IntegerVector cand_ptr, IntegerVector cand_idx, int n_universe, int n_perm);
RcppExport SEXP _tkoi_tkoi_sample_null(SEXP cand_ptrSEXP, SEXP cand_idxSEXP, SEXP n_universeSEXP, SEXP n_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cand_ptr(cand_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cand_idx(cand_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_universe(n_universeSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    rcpp_result_gen = Rcpp::wrap(tkoi_sample_null(cand_ptr, cand_idx, n_universe, n_perm));
    return rcpp_result_gen;
END_RCPP
}
// tkoi_total_memory
double tkoi_total_memory();
RcppExport SEXP _tkoi_tkoi_total_memory() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(tkoi_total_memory());
    return rcpp_result_gen;
END_RCPP
}
// tkoi_hardware_threads
int tkoi_hardware_threads();
RcppExport SEXP _tkoi_tkoi_hardware_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(tkoi_hardware_threads());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tkoi_tkoi_build_csr", (DL_FUNC) &_tkoi_tkoi_build_csr, 4},
    {"_tkoi_tkoi_ppr_null", (DL_FUNC) &_tkoi_tkoi_ppr_null, 12},
    {"_tkoi_tkoi_seed_reach", (DL_FUNC) &_tkoi_tkoi_seed_reach, 4},
    {"_tkoi_tkoi_sample_null", (DL_FUNC) &_tkoi_tkoi_sample_null, 4},
    {"_tkoi_tkoi_total_memory", (DL_FUNC) &_tkoi_tkoi_total_memory, 0},
    {"_tkoi_tkoi_hardware_threads", (DL_FUNC) &_tkoi_tkoi_hardware_threads, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tkoi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
