# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.tkoi_build_csr <- function(from, to, weight, n) {
    .Call(`_tkoi_tkoi_build_csr`, from, to, weight, n)
}

.tkoi_ppr_null <- function(csr, observed_node, observed_weight, null_node, null_weight, damping, tol, max_iter, n_threads, max_block, keep_null, progress = NULL) {
    .Call(`_tkoi_tkoi_ppr_null`, csr, observed_node, observed_weight, null_node, null_weight, damping, tol, max_iter, n_threads, max_block, keep_null, progress)
}

.tkoi_seed_reach <- function(row_ptr, col, seeds, n_threads) {
    .Call(`_tkoi_tkoi_seed_reach`, row_ptr, col, seeds, n_threads)
}

.tkoi_sample_null <- function(cand_ptr, cand_idx, n_universe, n_perm) {
    .Call(`_tkoi_tkoi_sample_null`, cand_ptr, cand_idx, n_universe, n_perm)
}

.tkoi_total_memory <- function() {
    .Call(`_tkoi_tkoi_total_memory`)
}

.tkoi_hardware_threads <- function() {
    .Call(`_tkoi_tkoi_hardware_threads`)
}

